// This file is @generated by prost-build.
/// Virtual Machine metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VmMd {
    #[prost(uint32, tag = "1")]
    pub main_template_id: u32,
    #[prost(uint32, tag = "2")]
    pub templates_num: u32,
    #[prost(uint32, tag = "3")]
    pub functions_num: u32,
    #[prost(uint32, tag = "4")]
    pub signals_num: u32,
    #[prost(uint32, tag = "5")]
    pub constants_num: u32,
    #[prost(map = "string, message", tag = "9")]
    pub inputs:
        ::std::collections::HashMap<::prost::alloc::string::String, super::SignalDescription>,
    #[prost(uint32, repeated, tag = "7")]
    pub witness_signals: ::prost::alloc::vec::Vec<u32>,
    #[prost(map = "uint32, message", tag = "8")]
    pub io_map: ::std::collections::HashMap<u32, IoDefs>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentTmpl {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub sub_cmp_idx: u64,
    #[prost(uint64, tag = "3")]
    pub number_of_cmp: u64,
    #[prost(string, tag = "4")]
    pub name_subcomponent: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub signal_offset: u64,
    #[prost(uint64, tag = "6")]
    pub signal_offset_jump: u64,
    #[prost(uint64, tag = "7")]
    pub template_id: u64,
    #[prost(bool, tag = "8")]
    pub has_inputs: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Template {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub code: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag = "3")]
    pub line_numbers: ::prost::alloc::vec::Vec<u64>,
    #[prost(message, repeated, tag = "4")]
    pub components: ::prost::alloc::vec::Vec<ComponentTmpl>,
    #[prost(uint64, tag = "5")]
    pub var_stack_depth: u64,
    #[prost(uint64, tag = "6")]
    pub number_of_inputs: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Function {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub code: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag = "4")]
    pub line_numbers: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IoDef {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(uint32, tag = "2")]
    pub offset: u32,
    #[prost(uint32, repeated, tag = "3")]
    pub lengths: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IoDefs {
    #[prost(message, repeated, tag = "1")]
    pub io_defs: ::prost::alloc::vec::Vec<IoDef>,
}
